# Site settings
title: Coding Adventures
header-img: img/home-bg.png
email: cvaleriac@hotmail.it
copyright_name: cvaleriac
description: > # this means to ignore newlines until "baseurl:"
  New Challenge
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cvaleriac
learn_profile: cvaleriac
email_username: cvaleriac@hotmail.it

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
